import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
   title: {
      default: "Next.js Demo",
      template: "%s | Next.js Demo",
   },
   description: "Generated by Next.js",
};

export default function RootLayout({
   children,
}: {
   children: React.ReactNode;
}) {
   return (
      <html lang="en">
         <body className="p-2">
            <header className="bg-blue-300 p-4">
               <h1>Header</h1>
            </header>
            {children}
            <footer className="p-4 bg-slate-200">
               <h1>footer</h1>
            </footer>
         </body>
      </html>
   );
}
